### ISSUE TITLE
Quickstart landing page

### ISSUE THREAD

**Issue by 3y3** [diplodoc-platform/diplodoc#4]
Allow to add new project to diplodoc service in three steps

- [x] Authorise with github
- [x] Create new gh repo from [diplodoc-template]()
- [x] Register new project in diplodoc system for created gh repo
- [ ] Register new project in diplodoc system for existed gh repo
- [ ] Fill initial info on project s3 bucket
