### ISSUE TITLE
Implement translation pipeline

### ISSUE THREAD

**Issue by 3y3** [diplodoc-platform/diplodoc#7]
Allow to translate initial documentation to other languages in automatic or semi automatic mode

- [x] Implement CommonMark translation fragments extraction and composition
- [x] Implement YFM translation fragments extraction and composition
- [ ] Implement precise inline markdown wrapping
- [x] Implement automatic translation API
  - [ ] Add documentation
  - [ ] Add tutorial for Yandex Translation API
  - [ ] Improve CLI integration
- [x] Implement semi automatic translation API
  - [ ] Add documentation
  - [ ] Add tutorial for SmartCat system
  - [ ] Improve CLI integration
